version: '3'
services:
  docker-volume-backup:
    build: .
    restart: always
    environment:
      - AUTH_USERNAME=user
      - AUTH_PASSWORD=pass
    ports:
      - "1999:1999"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  data: